server:
  port: 9992

# application.properties의 server.port=9992 과 같다.
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://1.220.247.78:3308/final2410_3
    username: final_2410_team3
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true



